male: 1
female: 0
date_format: "%m/%d/%Y"
date:
  formats:
    default: "%d/%m/%Y"
    short: "%b %d"
    long: "%B %d, %Y"
achievement:
  cancel_edit: "cancel_achievement_edit"
  cancel_new: "cancel_achievement_new"
certificate:
  maximum: 255
certificate_cancel:
  edit: "cancel_certificate_edit"
  new: "cancel_certificate_new"
selected: "1"
clubs:
  model:
    current_fall: "1"
    name_max_length: 150
    pos_max_length: 100
    cont_max_length: 5000
    cont_min_length: 20
experiences:
  cancel_edit: "cancel_experience_edit"
  cancel_new: "cancel_experience_new"
  model:
    name_max_length: 150
    company_max_length: 150
    detail_max_length: 5000
    detail_min_length: 20
pagination:
  jobs_perpage: 5
jobs:
  description:
    maximum_length: 255
employers:
  page: 10
bookmark:
  bookmarked: 0
  liked: 1
