male: 1
female: 0
date_format: "%m/%d/%Y"
date:
  formats:
    default: "%d/%m/%Y"
    short: "%b %d"
    long: "%B %d, %Y"
achievement:
  cancel_edit: "cancel_achievement_edit"
  cancel_new: "cancel_achievement_new"
certificate:
  maximum: 255
certificate_cancel:
  edit: "cancel_certificate_edit"
  new: "cancel_certificate_new"
